
-- Add traffic and ads columns to marketplace_reports
ALTER TABLE public.marketplace_reports
  ADD COLUMN IF NOT EXISTS page_views INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS unique_visitors INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS bounce_rate NUMERIC(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_spend NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_impressions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_clicks INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_roas NUMERIC(8,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ads_cpc NUMERIC(10,2) DEFAULT 0;
